<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>abc</string>
	</array>
	<key>name</key>
	<string>ABC Notation</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.namespace.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Namespace</string>
			<key>match</key>
			<string>(%)(abc(?:-\d\.\d)?)</string>
			<key>name</key>
			<string>meta.namespace.abc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.directive.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Directives</string>
			<key>match</key>
			<string>(%%)\s*(\w*)\b([^%\n\r]*)</string>
			<key>name</key>
			<string>meta.directive.abc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>%{1}(?!%|abc).*</string>
			<key>name</key>
			<string>comment.line.percentage.abc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bar lines</string>
			<key>match</key>
			<string>[\[:]*[|:][|\]:]*(\[?[0-9]+)?|(\[[0-9]+)</string>
			<key>name</key>
			<string>keyword.operator.abc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Header lines</string>
			<key>match</key>
			<string>^[A-Za-z]:([^%\\]*)</string>
			<key>name</key>
			<string>entity.name.function.abc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline fields</string>
			<key>match</key>
			<string>\[([A-Z]:)(.*?)\]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Notes</string>
			<key>match</key>
			<string>([_\^]{2}|=|[_=\^](?:\d*/*(?:\d*)?)|(?:\d(?!\.))+)?([A-Ga-g][,']*)((?:\d*/*(?:\d*)?)|(?:\d*&gt;*(?:\d*)?)|(?:\d*&lt;*(?:\d*)?)|(?:\d(?!\.))+)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Chord names + other annotations</string>
			<key>match</key>
			<string>[\"!].*?[\"!]</string>
			<key>name</key>
			<string>string.quoted.abc</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>%(?!%|abc).*</string>
			<key>name</key>
			<string>comment.line.percentage.abc</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.abc</string>
	<key>uuid</key>
	<string>431a5f26-5897-4146-8415-25a3c4b859c0</string>
</dict>
</plist>
