<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>abc</string>
	</array>
	<key>name</key>
	<string>ABC Notation</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#unparsed</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#escape</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bar lines</string>
			<key>match</key>
			<string>((?:\.?\|\|?|:*\|\]|\[\|:*|::|:+\||\|:+|\.?\||\[\|\])[1-9]?|(?::*\|[1-9](?:[-,][1-9])*))</string>
			<key>name</key>
			<string>keyword.operator.barline.abc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Header lines</string>
			<key>match</key>
			<string>^[A-Za-z]:([^%\\]*)</string>
			<key>name</key>
			<string>entity.name.function.abc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.inline-field.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.inline-field.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.inline-field.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline Fields</string>
			<key>match</key>
			<string>(\[[a-zA-Z&amp;&amp;[^IKXr]]:)(.*?)(\])</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.accidental.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.note.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.note-length.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Notes</string>
			<key>match</key>
			<string>([_\^]{2}|=|[_=\^](?:\d*/*(?:\d*)?)|(?:\d(?!\.))+)?([A-Ga-g][,']*)((?:\d*/*(?:\d*)?)|(?:\d*&gt;*(?:\d*)?)|(?:\d*&lt;*(?:\d*)?)|(?:\d(?!\.))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.chord.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Chord symbols and string annotations</string>
			<key>match</key>
			<string>(\")(.*)(\")</string>
			<key>name</key>
			<string>meta.code.string.chord.abc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\((?![\d!:]))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.slur.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Slurs</string>
			<key>end</key>
			<string>(\)(?!!))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.slur.abc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.code.slur.abc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#abc-code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[(?!(?:[|:\d])|(?:[A-Za-z]:)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.chord.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Chords</string>
			<key>end</key>
			<string>(\](?![|:\d]))</string>
			<key>name</key>
			<string>meta.code.chord.abc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.decoration.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.trait.decoration.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.decoration.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Decorations</string>
			<key>match</key>
			<string>(!)([[:alpha:]&amp;&amp;[^\s!]]*)(!)</string>
			<key>name</key>
			<string>meta.code.decoration.abc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line Break</string>
			<key>match</key>
			<string>(\$(?= ) +)</string>
			<key>name</key>
			<string>support.constant.line-break.abc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line Continue</string>
			<key>match</key>
			<string>(\/(?= ) +)</string>
			<key>name</key>
			<string>support.constant.line-continue.abc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#namespace</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>%(?!%|abc).*</string>
			<key>name</key>
			<string>comment.line.percentage.abc</string>
		</dict>
		<key>directive</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.directive.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Directives</string>
			<key>match</key>
			<string>(%%)\s*(\w*)\b([^%\n\r]*)</string>
			<key>name</key>
			<string>meta.directive.abc</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>(?:\\%)|(?:\\\\)|(?:\\u\h{4})|(?:\\[[:punct:]&amp;&amp;[\w]&amp;&amp;[^\s]]{2})|(?:&amp;\w+;)|(?:&amp;#\d+;)|(?:&amp;#x\h+;)</string>
			<key>name</key>
			<string>constant.character.escape.abc</string>
		</dict>
		<key>namespace</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.namespace.abc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Namespace</string>
			<key>match</key>
			<string>(%)(abc(?:-\d\.\d)?)</string>
			<key>name</key>
			<string>meta.namespace.abc</string>
		</dict>
		<key>note-length</key>
		<dict>
			<key>comment</key>
			<string>Note lengths</string>
			<key>match</key>
			<string>((?:\d*/*(?:\d*)?)|(?:\d*&gt;*(?:\d*)?)|(?:\d*&lt;*(?:\d*)?)|(?:\d(?!\.))+)</string>
			<key>name</key>
			<string>constant.numeric.note-length.abc</string>
		</dict>
		<key>spacing-length</key>
		<dict>
			<key>match</key>
			<string>(\d*(?:\.\d*)?(?:pt|in|cm)?\b)</string>
			<key>name</key>
			<string>constant.numeric.float.spacing-length.abc</string>
		</dict>
		<key>svg-directive</key>
		<dict>
			<key>begin</key>
			<string>(%%)\s*(beginsvg)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pseudo.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.function.abc punctuation.definition.sequence.begin.abc</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.xml</string>
			<key>end</key>
			<string>(%%)\s*(endsvg)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pseudo.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.function.abc punctuation.definition.sequence.end.abc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.svg.directive.abc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#_escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#abc-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#_directive</string>
				</dict>
			</array>
		</dict>
		<key>svg-instruction</key>
		<dict>
			<key>begin</key>
			<string>(^I:)\s*(beginsvg)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.instruction.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.function.abc punctuation.definition.sequence.begin.abc</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.xml</string>
			<key>end</key>
			<string>(^I:)\s*(endsvg)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.instruction.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.function.abc punctuation.definition.sequence.begin.abc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.svg.instruction.abc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
			</array>
		</dict>
		<key>text-directive</key>
		<dict>
			<key>begin</key>
			<string>^(%%)\s*(begintext)\b\s+((?:obeylines|fill|ragged|justify|align|skip)\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.directive.abc</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.free.abc</string>
			<key>end</key>
			<string>^(%%)\s*(endtext)\s*\n</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.abc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.text.directive.abc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
			</array>
		</dict>
		<key>text-instruction</key>
		<dict>
			<key>begin</key>
			<string>^(I:)\s*(begintext)\b\s+((?:obeylines|fill|ragged|justify|align|skip)\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.instruction.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.abc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.directive.abc</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.free.abc</string>
			<key>end</key>
			<string>^(I:)\s*(endtext)\s*\n</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.instruction.abc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.abc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.text.instruction.abc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
			</array>
		</dict>
		<key>unparsed</key>
		<dict>
			<key>begin</key>
			<string>^([^\s].*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.free-text.abc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>meta.free-text.abc</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.abc</string>
	<key>uuid</key>
	<string>431a5f26-5897-4146-8415-25a3c4b859c0</string>
</dict>
</plist>
