<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gcemode</string>
		<string>gcetheme</string>
	</array>
	<key>name</key>
	<string>GoCoEdit JSON</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#value</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#match</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.array.gce punctuation.definition.array.begin.gce</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.structure.array.gce</string>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.gce keyword.operator.array.gce</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.brackets.array.gce</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(,)</string>
					<key>name</key>
					<string>punctuation.separator.array.gce keyword.operator.value.gce</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([^\s\]])</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.gce</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.gce</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(//.*)</string>
					<key>name</key>
					<string>comment.line.double-slash.gce</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>(?:true|false|null)</string>
			<key>name</key>
			<string>constant.language.gce</string>
		</dict>
		<key>match</key>
		<dict>
			<key>begin</key>
			<string>"(match|regex)"\s*?:\s*(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.control.gce</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.gce punctuation.definition.regex.start.gce</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.gce</string>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.regex.end.gce string.quoted.double.gce</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.error.data.json-tmlanguage</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.escapedregexp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>comment</key>
			<string>handles integer and decimal numbers</string>
			<key>match</key>
			<string>(-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?)</string>
			<key>name</key>
			<string>constant.numeric.gce</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.gce</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>a JSON object</string>
			<key>contentName</key>
			<string>meta.structure.dictionary.gce</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.gce</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.object.gce</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gce</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.gce</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gce</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.key-value.gce</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
  (?:^\s*)?(\")
  (token(?:izer)?|name|ext|state|parse|regex|
   overwriteState|stateAfterMatch|recoverState|
   onlyOnLineStart|dash_docsets|symbol_search|hint|global)
  (\")\s*(:)</string>
					<key>name</key>
					<string>meta.structure.dictionary.value.gce</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.dictionary.pair.gce</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(,|(?=\}))</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.gce punctuation.definition.string.begin.gce</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.gce</string>
			<key>end</key>
			<string>(\")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gce string.quoted.double.gce</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.string.gce</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))</string>
					<key>name</key>
					<string>constant.character.escape.gce</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.gce</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gce</string>
	<key>uuid</key>
	<string>3e31b235-394a-4963-90cd-cccf56085c45</string>
</dict>
</plist>
