<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gcemode</string>
	</array>
	<key>name</key>
	<string>GoCoEdit Custom Mode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#value</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.gcemode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.gcemode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.gcemode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.gcemode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\]]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.gcemode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(/\*\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gcemode</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Block Documentation Comments</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gcemode</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.gcemode</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gcemode</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Block Comments</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gcemode</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.gcemode</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gcemode</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Line Comments</string>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.gcemode</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(?:true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.gcemode</string>
		</dict>
		<key>number</key>
		<dict>
			<key>comment</key>
			<string>handles integer and decimal numbers</string>
			<key>match</key>
			<string>(?x:-?(?:0|[1-9]\d*)
  (?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?)</string>
			<key>name</key>
			<string>constant.numeric.gcemode</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.gcemode</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>a JSON object</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.gcemode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.dictionary.gcemode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
  (?:^\s*)?(\")
  (token(?:izer)?|name|ext|state|parse|regex|
   overwriteState|stateAfterMatch|recoverState|
   onlyOnLineStart|dash_docsets|symbol_search|hint|global)
  (\")\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gcemode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.gcemode</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gcemode</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.key-value.gcemode</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.structure.dictionary.value.gcemode</string>
					<key>end</key>
					<string>(,)|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.pair.gcemode</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.key.gcemode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gcemode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gcemode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.gcemode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x:\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))</string>
					<key>name</key>
					<string>constant.character.escape.gcemode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.gcemode</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gcemode</string>
	<key>uuid</key>
	<string>3e31b235-394a-4963-90cd-cccf56085c45</string>
</dict>
</plist>
