<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fmt</string>
	</array>
	<key>name</key>
	<string>ABC Formatting Extension</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-content</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^\s*)?(%(?!abc))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fmt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.percentage.fmt</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fmt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.special-method.namespace.fmt</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:^\s*)?(?&gt;(%)(abc(?:-\d\.\d)?))</string>
					<key>name</key>
					<string>comment.line.namespace.fmt</string>
				</dict>
			</array>
		</dict>
		<key>directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?!(?:begin|end(?:text|svg|ps|js|md|ml))|postscript|ps)\w*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.word.directive.abc</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.directive.abc</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.directive.abc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
  (MIDI +
    (?:no)?barlines|bassprog|(?:no)?beataccents|beat(?:mod|string)?|
    bend(?:velocity|string)|chord(?:attack|name|program)|
    control(?:combo|string)?|deltaloudness|droneo(?:n|ff)|
    drum(?:on|off|bars|map)|expand|fermata(?:fixed|proportional)?|
    gchord(?:on|off)?|grace(?:divider)?|makechordchannels|pitchbend|
    portamento|program|ptstress|randomchordattack|ratio|stressmodel|
    snt|rtranspose|temperament(?:linear|equal|normal)|transpose|
    trim|vol(inc)?)\b</string>
					<key>name</key>
					<string>keyword.operator.word.directive.midi.abc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\d*(?:\.\d*)?(?:pt|in|cm)?)</string>
					<key>name</key>
					<string>constant.numeric.float.length-unit.abc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(true|false|yes|no|on|off)\b</string>
					<key>name</key>
					<string>storage.type.directive.abc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>embedded-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(begintext)\b(\s+(?:obeylines|fill|ragged|justify|align|skip))?\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.directive.abc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Typeset Text</string>
					<key>contentName</key>
					<string>string.unquoted.typeset.abc</string>
					<key>end</key>
					<string>^\s*(endtext)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.typeset.abc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(beginml)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Embedded HTML</string>
					<key>end</key>
					<string>^\s*(endml)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.html.abc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(beginjs)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Embedded JavaScript</string>
					<key>end</key>
					<string>^\s*(endjs)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.js.abc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(beginsvg)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Embedded SVG</string>
					<key>end</key>
					<string>^\s*(endsvg)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.percentage.abc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.svg.abc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(beginps)(\s+(?:nosvg))?\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.directive.abc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Embedded PostScript</string>
					<key>end</key>
					<string>^\s*(endps)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.ps.abc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.postscript</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(beginmd)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Embedded Markdown</string>
					<key>end</key>
					<string>^\s*(endmd)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.directive.abc</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Inline Postscript Instructions</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^\s*(postscript|ps)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.directive.abc</string>
								</dict>
							</dict>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.ps.abc</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.postscript</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fmt</string>
	<key>uuid</key>
	<string>972d5050-f5bb-4d36-b94e-b00079652038</string>
</dict>
</plist>
